export const products = [
  // Men Shell Jackets
  {
    name: "Summit Pro Shell",
    bio: "Lightweight, waterproof, and breathable with pit zips.",
    priceOld: 250,
    price: 175,
    category: ["clothing", "shell jackets", "sale"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-Summit-Pro-Shell.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-Summit-Pro-Shell-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false,
  },
  {
    name: "StormGuard 360",
    bio: "Windproof, reinforced hood, and waterproof zippers.",
    priceOld: undefined,
    price: 190,
    category: ["clothing", "shell jackets"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-StormGuard-360.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-StormGuard-360-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false,
  },
  {
    name: "Alpine Edge Jacket",
    bio: "Helmet-compatible hood and abrasion-resistant shoulders.",
    priceOld: undefined,
    price: 180,
    category: ["clothing", "shell jackets"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-Alpine-Edge-Jacket.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-Alpine-Edge-Jacket-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  
  {
    name: "TrailMaster Shell",
    bio: "Ultra-light, packable, and DWR-coated.",
    priceOld: 350,
    price: 300,
    category: ["clothing", "shell jackets", "members discount"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-TrailMaster-Shell.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-TrailMaster-Shell-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },
  {
    name: "Glacier Peak Shell",
    bio: "Seam-sealed with a storm flap for extreme weather.",
    priceOld: undefined,
    price: 270,
    category: ["clothing", "shell jackets", "best seller"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-Glacier-Peak-Shell.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-Glacier-Peak-Shell-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },  
  {
    name: "Ridge Runner Shell",
    bio: "Eco-friendly waterproofing and adjustable hem.",
    priceOld: 190,
    price: 169,
    category: ["clothing", "shell jackets", "sale"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-Ridge-Runner-Shell.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-Ridge-Runner-Shell-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  
  {
    name: "WildPeak Storm Shell",
    bio: "Powder skirt, ski pass pocket, and ventilation.",
    priceOld: undefined,
    price: 230,
    category: ["clothing", "shell jackets"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-WildPeak-Storm-Shell.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-WildPeak-Storm-Shell-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  
  {
    name: "Cascade Voyager Jacket",
    bio: "Welded seams and adjustable wrist gaiters.",
    priceOld: undefined,
    price: 210,
    category: ["clothing", "shell jackets", "new"],
    image: "images/shop/men/shell/Mens-Shell-Jackets-Cascade-Voyager-Jacket.png",
    imagehover: "images/shop/men/shell/Mens-Shell-Jackets-Cascade-Voyager-Jacket-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },  

  // Men Insulated Jackets

  {
    name: "Arctic Shield Jacket",
    bio: "Lightweight, water-resistant, and insulated for warmth.",
    priceOld: undefined,
    price: 210,
    category: ["clothing", "insulated jackets", "new"],
    image: "images/shop/men/insulated/Mens-Insulated-Jackets-Arctic-Shield-Jacket.png",
    imagehover: "images/shop/men/insulated/Mens-Insulated-Jackets-Arctic-Shield-Jacket-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false,
  },
  {
    name: "Summit Down Parka",
    bio: "800-fill goose down with a windproof outer shell.",
    priceOld: 245,
    price: 199,
    category: ["clothing", "insulated jackets", "members discount"],
    image: "images/shop/men/insulated/Mens-Insulated-Jackets-Summit-Down-Parka.png",
    imagehover: "images/shop/men/insulated/Mens-Insulated-Jackets-Summit-Down-Parka-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },
  {
    name: "Everest Thermal Jacket",
    bio: "Fleece-lined with a weatherproof shell.",
    priceOld: undefined,
    price: 500,
    category: ["clothing", "insulated jackets"],
    image: "images/shop/men/insulated/Mens-Insulated-Jackets-Everest-Thermal-Jacket.png",
    imagehover: "images/shop/men/insulated/Mens-Insulated-Jackets-Everest-Thermal-Jacket-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  
  {
    name: "Tundra Core Jacket",
    bio: "Windproof with a moisture-wicking liner.",
    priceOld: undefined,
    price: 239,
    category: ["clothing", "insulated jackets"],
    image: "images/shop/men/insulated/Mens-Insulated-Jackets-Tundra-Core-Jacket.png",
    imagehover: "images/shop/men/insulated/Mens-Insulated-Jackets-Tundra-Core-Jacket-Hover.png",
    sale: false,
    new: true,
    bestSeller: true,
    membersExclusive: false
  },  

  // Men Pants

  {
    name: "Summit Trail Pants ",
    bio: "Durable, lightweight for hiking and tough terrain.",
    priceOld: undefined,
    price: 120,
    category: ["clothing", "pants"],
    image: "images/shop/men/pants/Mens-Pants-Summit-Trail-Pants.png",
    imagehover: "images/shop/men/pants/Mens-Pants-Summit-Trail-Pants-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false,
  },
  {
    name: "RidgeLine Adventure Trousers",
    bio: "Quick-dry, moisture-wicking, and versatile.",
    priceOld: undefined,
    price: 110,
    category: ["clothing", "pants"],
    image: "images/shop/men/pants/Mens-Pants-RidgeLine-Adventure-Trousers.png",
    imagehover: "images/shop/men/pants/Mens-Pants-RidgeLine-Adventure-Trousers-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  
  {
    name: "Alpine Trekking Pants",
    bio: "Stretchy and weather-resistant for alpine hikes.",
    priceOld: 85,
    price: 60,
    category: ["clothing", "pants", "sale"],
    image: "images/shop/men/pants/Mens-Pants-Alpine-Trekking-Pants.png",
    imagehover: "images/shop/men/pants/Mens-Pants-Alpine-Trekking-Pants-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  
  {
    name: "Everest Pro Hiking Pants",
    bio: "Reinforced knees and breathable fabric.",
    priceOld: undefined,
    price: 135,
    category: ["clothing", "pants", "best seller"],
    image: "images/shop/men/pants/Mens-Pants-Everest-Pro-Hiking-Pants.png",
    imagehover: "images/shop/men/pants/Mens-Pants-Everest-Pro-Hiking-Pants-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },  
  {
    name: "WildPeak Outdoor Pants",
    bio: "Waterproof, breathable for mountain trails.",
    priceOld: 220,
    price: 180,
    category: ["clothing", "pants", "members discount"],
    image: "images/shop/men/pants/Mens-Pants-WildPeak-Outdoor-Pants.png",
    imagehover: "images/shop/men/pants/Mens-Pants-WildPeak-Outdoor-Pants-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },  
  {
    name: "MountainQuest Cargo Pants",
    bio: "Comfortable cargo pants with multiple pockets.",
    priceOld: undefined,
    price: 125,
    category: ["clothing", "pants", "new"],
    image: "images/shop/men/pants/Mens-Pants-MountainQuest-Cargo-Pants.png",
    imagehover: "images/shop/men/pants/Mens-Pants-MountainQuest-Cargo-Pants-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },

  // Men Fleece

  {
    name: "Arctic Breeze Fleece",
    bio: "Soft fleece with a zippered collar and perfect for light outdoor activities.",
    priceOld: undefined,
    price: 95,
    category: ["clothing", "fleece"],
    image: "images/shop/men/fleece/Mens-Fleece-Arctic-Breeze-Fleece.png",
    imagehover: "images/shop/men/fleece/Mens-Fleece-Arctic-Breeze-Fleece-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false,
  },
  {
    name: "Cobalt Trail Fleece",
    bio: "Warm and breathable, designed for all-day wear during colder days.",
    priceOld: undefined,
    price: 120,
    category: ["clothing", "fleece"],
    image: "images/shop/men/fleece/Mens-Fleece-Cobalt-Trail-Fleece.png",
    imagehover: "images/shop/men/fleece/Mens-Fleece-Cobalt-Trail-Fleece-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },
  {
    name: "Alpine Pulse Fleece",
    bio: "Lightweight yet warm, with an adjustable hem for a customized fit.",
    priceOld: undefined,
    price: 130,
    category: ["clothing", "fleece", "best seller"],
    image: "images/shop/men/fleece/Mens-Fleece-Alpine-Pulse-Fleece.png",
    imagehover: "images/shop/men/fleece/Mens-Fleece-Alpine-Pulse-Fleece-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  
  // Men Base Layers

  {
    name: "SummitTech Base Layer",
    bio: "Compression fit for muscle support and temperature regulation.",
    priceOld: 100,
    price: 80,
    category: ["clothing", "base layer", "members discount"],
    image: "images/shop/men/baselayer/Mens-Baselayer-SummitTech-Base-Layer.png",
    imagehover: "images/shop/men/baselayer/Mens-Baselayer-SummitTech-Base-Layer-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true,
  },
  {
    name: "GlacierLite Base Layer",
    bio: "Ultra-soft with a smooth finish, providing maximum comfort.",
    priceOld: undefined,
    price: 75,
    category: ["clothing", "base layer"],
    image: "images/shop/men/baselayer/Mens-baselayer-GlacierLite-Base-Layer.png",
    imagehover: "images/shop/men/baselayer/Mens-baselayer-GlacierLite-Base-Layer-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  
  // Men Shirts & Tops

  {
    name: "SummitTech T-Shirt",
    bio: "Breathable, moisture-wicking fabric for active days.",
    priceOld: 45,
    price: 35,
    category: ["clothing", "shirts & tops", "sale"],
    image: "images/shop/men/shirt&tops/Mens-shirt&tops-SummitTech-T-Shirt.png",
    imagehover: "images/shop/men/shirt&tops/Mens-shirt&tops-SummitTech-T-Shirt-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false,
  },
  {
    name: "Alpine Flex Hoodie",
    bio: "Soft fleece-lined hoodie with a kangaroo pocket and adjustable drawstring.",
    priceOld: undefined,
    price: 60,
    category: ["clothing", "shirts & tops", "best seller"],
    image: "images/shop/men/shirt&tops/Mens-shirt&tops-Alpine-Flex-Hoodie.png",
    imagehover: "images/shop/men/shirt&tops/Mens-shirt&tops-Alpine-Flex-Hoodie-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },
  {
    name: "Mountain Escape Tank",
    bio: "Light, airy tank top perfect for hot weather adventures.",
    priceOld: 30,
    price: 22,
    category: ["clothing", "shirts & tops", "sale"],
    image: "images/shop/men/shirt&tops/Mens-shirt&tops-Mountain-Escape-Tank.png",
    imagehover: "images/shop/men/shirt&tops/Mens-shirt&tops-Mountain-Escape-Tank-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "TrailTech Long Sleeve",
    bio: "Comfortable long sleeve shirt with moisture-wicking fabric.",
    priceOld: undefined,
    price: 40,
    category: ["clothing", "shirts & tops"],
    image: "images/shop/men/shirt&tops/Mens-shirt&tops-TrailTech-Long-Sleeve.png",
    imagehover: "images/shop/men/shirt&tops/Mens-shirt&tops-TrailTech-Long-Sleeve-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Wild Horizon Henley",
    bio: "Comfortable henley style shirt with a touch of stretch.",
    priceOld: undefined,
    price: 50,
    category: ["clothing", "shirts & tops"],
    image: "images/shop/men/shirt&tops/Mens-shirt&tops-Wild-Horizon-Henley.png",
    imagehover: "images/shop/men/shirt&tops/Mens-shirt&tops-Wild-Horizon-Henley-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },

  // Men Shorts

  {
    name: "SummitTrail Cargo Shorts",
    bio: "Durable, lightweight shorts with multiple pockets for storage.",
    priceOld: 50,
    price: 40,
    category: ["clothing", "shorts", "sale"],
    image: "images/shop/men/shorts/Mens-shorts-SummitTrail-Cargo-Shorts.png",
    imagehover: "images/shop/men/shorts/Mens-shorts-SummitTrail-Cargo-Shorts-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "RidgeLine Hiking Shorts",
    bio: "Quick-drying fabric with an adjustable waistband for comfort.",
    priceOld: undefined,
    price: 45,
    category: ["clothing", "shorts"],
    image: "images/shop/men/shorts/Mens-shorts-RidgeLine-Hiking-Shorts.png",
    imagehover: "images/shop/men/shorts/Mens-shorts-RidgeLine-Hiking-Shorts-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "MountainFlex Sports Shorts",
    bio: "Breathable and flexible for active sports and outdoor adventures.",
    priceOld: undefined,
    price: 40,
    category: ["clothing", "shorts", "new"],
    image: "images/shop/men/shorts/Mens-shorts-MountainFlex-Sports-Shorts.png",
    imagehover: "images/shop/men/shorts/Mens-shorts-MountainFlex-Sports-Shorts-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  
  // Men Daypacks

  {
    name: "Alpine Horizon Backpack",
    bio: "Multi-compartment daypack with hydration reservoir sleeve.",
    priceOld: undefined,
    price: 200,
    category: ["packs", "daypacks", "new"],
    image: "images/shop/men/daypacks/Mens-daypacks-Alpine-Horizon-Backpack.png",
    imagehover: "images/shop/men/daypacks/Mens-daypacks-Alpine-Horizon-Backpack-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Tundra Explorer Pack",
    bio: "Water-resistant and durable, designed for the toughest conditions.",
    priceOld: undefined,
    price: 250,
    category: ["packs", "daypacks", "best seller"],
    image: "images/shop/men/daypacks/Mens-daypacks-Tundra-Explorer-Pack.png",
    imagehover: "images/shop/men/daypacks/Mens-daypacks-Tundra-Explorer-Pack-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },
  {
    name: "WildPeak Daypack",
    bio: "Lightweight with adjustable straps and a large main compartment.",
    priceOld: undefined,
    price: 145,
    category: ["packs", "daypacks"],
    image: "images/shop/men/daypacks/Mens-daypacks-WildPeak-Daypack.png",
    imagehover: "images/shop/men/daypacks/Mens-daypacks-WildPeak-Daypack-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  
  // Men Multi-Day Packs

  {
    name: "Summit Expedition Pack",
    bio: "Large capacity with multiple compartments and a hydration system.",
    priceOld: undefined,
    price: 350,
    category: ["packs", "multi-day"],
    image: "images/shop/men/multi-day/Mens-multi-day-Summit-Expedition-Pack.png",
    imagehover: "images/shop/men/multi-day/Mens-multi-day-Summit-Expedition-Pack-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Everest Pro Trek Pack",
    bio: "Durable, weather-resistant, and designed for extended expeditions.",
    priceOld: undefined,
    price: 420,
    category: ["packs", "multi-day", "new"],
    image: "images/shop/men/multi-day/Mens-multi-day-Everest-Pro-Trek-Pack.png",
    imagehover: "images/shop/men/multi-day/Mens-multi-day-Everest-Pro-Trek-Pack-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Tundra Explorer 60L Pack",
    bio: "60L capacity, optimized for comfort and long-term use.",
    priceOld: 500,
    price: 450,
    category: ["packs", "multi-day", "sale"],
    image: "images/shop/men/multi-day/Mens-multi-day-Tundra-Explorer-60L-Pack.png",
    imagehover: "images/shop/men/multi-day/Mens-multi-day-Tundra-Explorer-60L-Pack-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Alpine Pro 75L Hiking Pack",
    bio: "Heavy-duty pack with adjustable straps and a rain cover.",
    priceOld: undefined,
    price: 380,
    category: ["packs", "multi-day", "best seller"],
    image: "images/shop/men/multi-day/Mens-multi-day-Alpine-Pro-75L-Hiking-Pack.png",
    imagehover: "images/shop/men/multi-day/Mens-multi-day-Alpine-Pro-75L-Hiking-Pack-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },

  // Men Travel & Commute Packs

  {
    name: "Metro Daypack",
    bio: "Compact, water-resistant, and perfect for daily city commutes.",
    priceOld: 150,
    price: 130,
    category: ["packs", "travel & commute", "sale"],
    image: "images/shop/men/travel-commute/Mens-travel-commute-Metro-Daypack.png",
    imagehover: "images/shop/men/travel-commute/Mens-travel-commute-Metro-Daypack-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  

  // Men Boots

  {
    name: "Summit Trekker Boots",
    bio: "Waterproof, breathable with a cushioned insole for comfort.",
    priceOld: undefined,
    price: 180,
    category: ["footwear", "boots"],
    image: "images/shop/men/boots/Mens-Boots-Summit-Trekker-Boots.png",
    imagehover: "images/shop/men/boots/Mens-Boots-Summit-Trekker-Boots-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Alpine Expedition Boots",
    bio: "Insulated with a rubber outsole for grip on icy surfaces.",
    priceOld: 220,
    price: 190,
    category: ["footwear", "boots", "sale"],
    image: "images/shop/men/boots/Mens-Boots-Alpine-Expedition-Boots.png",
    imagehover: "images/shop/men/boots/Mens-Boots-Alpine-Expedition-Boots-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Everest Pro Hiking Boots",
    bio: "Durable leather construction with waterproof lining.",
    priceOld: undefined,
    price: 250,
    category: ["footwear", "boots", "new"],
    image: "images/shop/men/boots/Mens-Boots-Everest-Pro-Hiking-Boots.png",
    imagehover: "images/shop/men/boots/Mens-Boots-Everest-Pro-Hiking-Boots-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Trailblazer Hiking Boots",
    bio: "Flexible with enhanced ankle support for rough terrains.",
    priceOld: undefined,
    price: 180,
    category: ["footwear", "boots", "best seller"],
    image: "images/shop/men/boots/Mens-Boots-Trailblazer-Hiking-Boots.png",
    imagehover: "images/shop/men/boots/Mens-Boots-Trailblazer-Hiking-Boots-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },
  {
    name: "Tundra Trek Boots",
    bio: "Insulated with thermal lining for extreme cold weather conditions.",
    priceOld: 280,
    price: 240,
    category: ["footwear", "boots", "members discount"],
    image: "images/shop/men/boots/Mens-Boots-Tundra-Trek-Boots.png",
    imagehover: "images/shop/men/boots/Mens-Boots-Tundra-Trek-Boots-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },
  
  // Men Shoes

  {
    name: "Pioneer Trail Running Shoes",
    bio: "Lightweight, breathable, with superior traction for trail runs.",
    priceOld: undefined,
    price: 120,
    category: ["footwear", "shoes"],
    image: "images/shop/men/shoes/Mens-Shoes-Pioneer-Trail-Running-Shoes.png",
    imagehover: "images/shop/men/shoes/Mens-Shoes-Pioneer-Trail-Running-Shoes-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Summit Sport Shoes",
    bio: "Breathable mesh upper with a slip-resistant sole.",
    priceOld: 110,
    price: 95,
    category: ["footwear", "shoes", "members discount"],
    image: "images/shop/men/shoes/Mens-Shoes-Summit-Sport-Shoes.png",
    imagehover: "images/shop/men/shoes/Mens-Shoes-Summit-Sport-Shoes-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },  

  // Men Gloves

  {
    name: "ArcticGrip Gloves",
    bio: "Insulated and touchscreen-compatible for extreme cold weather.",
    priceOld: undefined,
    price: 40,
    category: ["accessories", "gloves"],
    image: "images/shop/men/gloves/Mens-Gloves-ArcticGrip-Gloves.png",
    imagehover: "images/shop/men/gloves/Mens-Gloves-ArcticGrip-Gloves-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Summit Xtreme Gloves",
    bio: "Waterproof and windproof with a fleece lining for warmth.",
    priceOld: 55,
    price: 45,
    category: ["accessories", "gloves", "sale"],
    image: "images/shop/men/gloves/Mens-Gloves-Summit-Xtreme-Gloves.png",
    imagehover: "images/shop/men/gloves/Mens-Gloves-Summit-Xtreme-Gloves-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "TundraPro Gloves",
    bio: "Durable leather palm with thermal insulation for winter sports.",
    priceOld: 70,
    price: 60,
    category: ["accessories", "gloves", "members discount"],
    image: "images/shop/men/gloves/Mens-Gloves-TundraPro-Gloves.png",
    imagehover: "images/shop/men/gloves/Mens-Gloves-TundraPro-Gloves-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },
  
  // Men Toques & Beanies
  {
    name: "SnowPeak Beanie",
    bio: "Soft, stretchy knit for warmth and comfort in cold weather.",
    priceOld: undefined,
    price: 35,
    category: ["accessories", "toques & beanies"],
    image: "images/shop/men/toques&beanies/Mens-Toques-SnowPeak-Beanie.png",
    imagehover: "images/shop/men/toques&beanies/Mens-Toques-SnowPeak-Beanie-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "Everest Warm Knit Beanie",
    bio: "Cozy wool blend with a cuffed design for a snug fit.",
    priceOld: 55,
    price: 40,
    category: ["accessories", "toques & beanies", "sale"],
    image: "images/shop/men/toques&beanies/Mens-Toques-Everest-Warm-Knit-Beanie.png",
    imagehover: "images/shop/men/toques&beanies/Mens-Toques-Everest-Warm-Knit-Beanie-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "AlpineFlex Beanie",
    bio: "Stretchy, moisture-wicking fabric with a reflective logo for visibility.",
    priceOld: undefined,
    price: 45,
    category: ["accessories", "toques & beanies", "best seller"],
    image: "images/shop/men/toques&beanies/Mens-Toques-AlpineFlex-Beanie.png",
    imagehover: "images/shop/men/toques&beanies/Mens-Toques-AlpineFlex-Beanie-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },
  {
    name: "TundraLuxe Knit Hat",
    bio: "Insulated and fleece-lined for maximum warmth and comfort.",
    priceOld: 70,
    price: 60,
    category: ["accessories", "toques & beanies", "members discount"],
    image: "images/shop/men/toques&beanies/Mens-Toques-TundraLuxe-Knit-Hat.png",
    imagehover: "images/shop/men/toques&beanies/Mens-Toques-TundraLuxe-Knit-Hat-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },
  {
    name: "PeakMaster Beanie",
    bio: "Merino wool beanie with a breathable, snug fit.",
    priceOld: undefined,
    price: 38,
    category: ["accessories", "toques & beanies"],
    image: "images/shop/men/toques&beanies/Mens-Toques-PeakMaster-Beanie.png",
    imagehover: "images/shop/men/toques&beanies/Mens-Toques-PeakMaster-Beanie-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },

  // Men Hats & Caps
  {
    name: "Explorer Expedition Hat",
    bio: "Wide-brim hat with UV protection and water-resistant fabric.",
    priceOld: undefined,
    price: 40,
    category: ["accessories", "hats & caps", "best seller"],
    image: "images/shop/men/hats&caps/Mens-Hats-Explorer-Expedition-Hat.png",
    imagehover: "images/shop/men/hats&caps/Mens-Hats-Explorer-Expedition-Hat-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },
  {
    name: "Mountain Summit Cap",
    bio: "Adjustable cap with a sleek design and moisture-wicking fabric.",
    priceOld: 28,
    price: 25,
    category: ["accessories", "hats & caps", "members discount"],
    image: "images/shop/men/hats&caps/Mens-Hats-Mountain-Summit-Cap.png",
    imagehover: "images/shop/men/hats&caps/Mens-Hats-Mountain-Summit-Cap-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: true
  },
  {
    name: "Alpine Ridge Hat",
    bio: "Packable, durable hat designed for the adventurer on the go.",
    priceOld: undefined,
    price: 38,
    category: ["accessories", "hats & caps"],
    image: "images/shop/men/hats&caps/Mens-Hats-Alpine-Ridge-Hat.png",
    imagehover: "images/shop/men/hats&caps/Mens-Hats-Alpine-Ridge-Hat-Hover.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  

  // Men Socks
  
  {
    name: "Alpine Performance Socks",
    bio: "Breathable and moisture-wicking socks for long hikes.",
    priceOld: undefined,
    price: 20,
    category: ["accessories", "socks"],
    image: "images/shop/men/socks/Mens-Socks-Alpine-Performance-Socks.png",
    imagehover: "images/shop/men/socks/Mens-Socks-Alpine-Performance-Socks-Hover.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "TundraTech Wool Socks",
    bio: "Insulated wool socks to keep your feet warm and dry in cold weather.",
    priceOld: undefined,
    price: 22,
    category: ["accessories", "socks", "best seller"],
    image: "images/shop/men/socks/Mens-Socks-TundraTech-Wool-Socks.png",
    imagehover: "images/shop/men/socks/Mens-Socks-TundraTech-Wool-Socks-Hover.png",
    sale: false,
    new: false,
    bestSeller: true,
    membersExclusive: false
  },
  {
    name: "Summit Trail Socks",
    bio: "Durable, cushioned socks designed for rugged terrain.",
    priceOld: 25,
    price: 18,
    category: ["accessories", "socks", "sale"],
    image: "images/shop/men/socks/Mens-Socks-Summit-Trail-Socks.png",
    imagehover: "images/shop/men/socks/Mens-Socks-Summit-Trail-Socks-Hover.png",
    sale: true,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },  

  // Men Product Care
  {
    name: "EcoTech Fabric Cleaner",
    bio: "Gentle yet effective cleaner for outdoor gear, environmentally friendly and safe for all fabrics.",
    priceOld: undefined,
    price: 15,
    category: ["accessories", "product care"],
    image: "images/shop/men/product-care/EcoTech-Fabric-Cleaner.png",
    imagehover: "images/shop/men/product-care/EcoTech-Fabric-Cleaner.png",
    sale: false,
    new: false,
    bestSeller: false,
    membersExclusive: false
  },
  {
    name: "BootGuard Waterproofing Spray",
    bio: "Protective spray that waterproofs and conditions leather and fabric boots, keeping your gear dry and in top condition.",
    priceOld: undefined,
    price: 18,
    category: ["accessories", "product care", "new"],
    image: "images/shop/men/product-care/EcoTech-Fabric-Cleaner.png",
    imagehover: "images/shop/men/product-care/EcoTech-Fabric-Cleaner.png",
    sale: false,
    new: true,
    bestSeller: false,
    membersExclusive: false
  }
  

];
